### ISSUE TITLE
on version 5.0  datepicker calendar month view appears behind navigation bar

### ISSUE THREAD

**Issue by drirem0** [infor-cloud/m3-h5-sdk#104]
[datepicker calendar view appears behind navigation bar.docx](https://github.com/infor-cloud/m3-h5-sdk/files/6897340/datepicker.calendar.view.appears.behind.navigation.bar.docx)

I just installed the new H5SDK version 5. I did notice that the datepicker monthly calendar view appears behind the navigation bar. 
Please advise the best solution here.   I tried to see if I could do something with z-index 

Thanks 
remco

**Comment by drirem0** [comment]
Hopefully I'll get an update soon on this one please ?  Even if it's a simple workaround we can do to fix this for the time being. 
Thanks very much 
Remco

**Comment by anhallbe** [comment]
Hi!
Questions / support / bugs related to the IDS components should go here: https://github.com/infor-design/enterprise-ng/issues

...or the MS Teams channel for IDS.

Side-note: In the future, it is better to write down the repro steps with images/gifs/videos etc in the GitHub issue directly rather than posting an MS Word document.

I'm closing this since the question is better suited for the IDS project rather than this one. Hope you're able to resolve the issue!
