### ISSUE TITLE
New versions in boilerplate

### ISSUE THREAD

**Issue by stewrutledge** [infor-cloud/m3-h5-sdk#129]
The packages provided in the package.json created by odin are getting pretty out of date, for example rxjs 6. Is there any plan to update these dependencies? Do the @infor-up package work with later versions that what are used in the boilerplate?

**Comment by jriedel-osp** [comment]
I have the same issue. Is there a plan to update the dependencies of odin?

**Comment by anhallbe** [comment]
Hi!
Yes there is a plan to update to Angular 14 and the latest IDS.

Unfortunately development has been on hold for a while because of other priorities. Sorry for the inconvenience!

**Comment by swuendri** [comment]
Let me know @anhallbe, if I can support development.

**Comment by anhallbe** [comment]
I just did some upgrades and created a pre-release (`@next`). It needs to be properly teste before I bump it to `latest`, but you can try it out:

1. Install the latest pre-release of the CLI:
```bash
# Should install version 6.0.0-next.1
npm i -g @infor-up/m3-odin-cli@next
```
2. Upgrade from Angular 12 to Angular 13, because `ng update` doesn't support skipping versions:
```bash
# NOTE: I needed --force to deal with npm peerDependencies shenanigans
ng update @angular/core@13 @angular/cli@13 --force
```
3. Commit or stage changes so that the working dir is clean. This might also be a good time to inspect the changes done by `ng update` and make sure things work reasonably well.
4. Upgrade from Angular 13 to Angular 14, with the pre-release of Odin and some other deps:
```bash
ng update @angular/core@14 @angular/cli@14 ids-enterprise-ng@14 rxjs@7 typescript @infor-up/m3-odin@next @infor-up/m3-odin-angular@next 
```
5. Inspect changes, test etc.
6. Done!

Note: The latest Angular, typescript and other dependencies probably won't work with older NodeJS versions. Upgrade to LTS

**Comment by anhallbe** [comment]
By the way @swuendri I'm on PTO right now so any help with testing etc would be much appreciated! :)

There are a lot of things on my wish-list for this project, but very little time to implement them. Contributions would be welcome! Although I'm aware that the documentation for new contributors is pretty much non-existent.

**Comment by swuendri** [comment]
Hi @anhallbe, okay I will do some manual tests but also start to write automated tests for m3-odin stuff.

I prepared also one contribution (https://github.com/infor-cloud/m3-h5-sdk/pull/127) according to the wish-list. Please have a look at it and send feedback, if this is the right direction.

**Comment by swuendri** [comment]
Hi @anhallbe, please see https://github.com/infor-cloud/m3-h5-sdk/pull/140 for first result regarding odin tests.

**Comment by stewrutledge** [comment]
Is there any more work on this? The version of angular packaged (and that odin is dependent on) will no longer be supported in a month.

https://angular.io/guide/releases

We have a lot of projects lined up and our current options are:

1. Use the stable tooling and build something that will no longer be supported in a month
2. Use an unstable release and hope for the best
3. Build our own tooling that we can keep updated.

**Comment by anhallbe** [comment]
6.0.0 is now released! See [CHANGELOG](https://github.com/infor-cloud/m3-h5-sdk/blob/master/CHANGELOG.md)

Sorry for the long, long, long delay on this.

There is, unfortunately, very little time to work on this project from my side.

Hopefully we can get some [builders](https://github.com/infor-cloud/m3-h5-sdk/pull/127) working so that versions of Angular, IDS & Odin is a bit more disconnected, which should making upgrades a lot easier. Huge thank you to @swuendri for the contributions!
