### ISSUE TITLE
version 7.0.0 with no Material support

### ISSUE THREAD

**Issue by pravnborg** [infor-cloud/m3-h5-sdk#201]
## Description
I can see you have disabled the Material opportunity.
I have been very happy with Material, and have used it for all my SDK's
Can I in any way make a 7.0.0 SDK Material SDK. Maybe after Odin build - make some manual steps? Where I can get rid of all IDS Design system?
 
## Versions
H5 Odin SDK 7.0.0

**Comment by pravnborg** [comment]
Rephrased:
I can see you have disabled the Material opportunity.
I have been very happy with Material, and have used it for all my SDK's
Can I in any way make a 7.0.0 SDK Material SDK. 
Maybe after Odin new - make some manual steps? Where I can get rid of all IDS Design system?

**Comment by whernebrink** [comment]
Hi,

Yes, since main applications created with this SDK are supposed to run in the context of Infor OS, following the same design system (i.e. IDS) for a consistent user experience, is recommended. That is why we decided to remove the "support"/examples from the SDK. 

You could manually add material design [Get Started](https://material.angular.io/guide/getting-started) if you wanted to, but we would ask you to reconsider, if your app is going to run inside Infor OS or in the H5 client. 

Thanks.
