### ISSUE TITLE
Is there a proper way to set Infor M3 tab title

### ISSUE THREAD

**Issue by hldarshana** [infor-cloud/m3-h5-sdk#22]
Is there any configuration or a function to change the Infor M3 tab titile? It shows just a part of the  application url every time after install the application.. Please refer the attachment..

![Infor M3 Tab Title](https://user-images.githubusercontent.com/60569119/74324689-68bb2e80-4dad-11ea-87e6-72000114cee6.jpg)

**Comment by karinpb** [comment]
This question is probably more suitable in the [Infor Community, M3 developer group](https://community.inforxtreme.com/infor-developers/f/m3-development) since it is not related directly to the m3-h5-sdk but more to how the M3 H5 application is opened. You don't mention how the application is launched, which is important information in this scenario.

If it is launched with ScriptUtil.Launch("url"), then the title will not be set. I can ask the H5 team to add an extra parameter for the name of the application or you can simply try and see if a global function launchTask("url","title") is available in the version you are using. Please note that launchTask as far as I know is not documented as a public API in the H5 Script developers guide which means that it can actually change.

If it is launched through the StartPage screen in H5 then the name of the link in the widget should be used and if it isn't then H5 needs to be upgraded to the latest fix/version.

**Comment by hldarshana** [comment]
Hi karinpb, we are using Link Manager in Infor M3 to launch application.

**Comment by karinpb** [comment]
In that case you need to report it as a bug for H5 in Infor Xtreme support portal. I don't know if this would be something that has been corrected recently. I know we have had some changes in this area.
