### ISSUE TITLE
Current company / division is not picked up

### ISSUE THREAD

**Issue by aleste37** [infor-cloud/m3-h5-sdk#27]
## Description
Web app process is to use the user's current company/division. But it seems it is not picked up by the sdk.

                       this.userService.getUserContext().subscribe((userContext: IUserContext) => {

when the user used mforms://cmp650100 to change session from cmp100100, the userContext doesn't pick it up 

## Versions
This is on M3 multi-tenant, NZ, 2020-0320.
@infor-up/m3-odin and @infor-up/m3-odin-angular is 2.2.0

**Comment by karinpb** [comment]
Hi,
The scenario is that the Application is opened within the tab set of the H5 client. When there are open tabs the H5 client should not allow the user to change company and division. I will need to actually check this with the H5 team but basically if that is not the case then I will create a report and ask them to fix it.

Generally it is not allowed to change company and division in the session if there are active programs. The H5 SDK application might itself have active programs (not likely at all, but it is possible). Giving that background there were never a need to implement a notification for change of company and division. The UserService will only get the usercontext once (and it will reuse what is currently active in H5 ) but there is no need to push a new user context when the company and division is changed because the application (tab in H5) will be closed when the company and division is changed.

If you are saying that this is not the case in cloud then I will report it and the H5 client should not call the server with a change company /division if there are currently open tabs in the H5 client.

**Comment by aleste37** [comment]
Hi Karin,

The client's use case opened M3 H5, switch company/divisions, then straight to the web app.
So standard M3 UI before that makes sure you don't have any programs open during company/division changes doesn't have a reason to run.

Regards,
Jonathan

**Comment by karinpb** [comment]
Yes. That scenario should be supported. I'm thinking it could be the setAliases that are incorrect. @anhallbe Can you please have a look at this scenario? (When you have time)

**Comment by karinpb** [comment]
@anhallbe  please check and compare with the name of the current division and company. According to this post the names are OK but the current cono and divi is incorrect. https://community.inforxtreme.com/infor-developers/f/m3-development/13755/infor-m3-odin-2-2-0---userservice-getusercontext-doesn-t-not-return-the-correct-value-of-user-context

**Comment by anhallbe** [comment]
Fixed in 2.2.1

**Comment by aleste37** [comment]
@anhallbe - thank you

**Comment by mbenmoussati** [comment]
Hi @anhallbe @karinpb .
I always got an error with userService. It is related to the but retrieved by @anhallbe with the CSRF
My log :
UserService {logPrefix: "[UserService] ", instance: UserServiceCore}
logPrefix: "[UserService] "
instance: UserServiceCore
logPrefix: "[UserServiceCore] "
miService: MIService {logPrefix: "[MIService] ", instance: MIServiceCore}
isUserContextAvailable: true
queue: []
isExecuting: false
isMessagePending: false
userContext: UserContext
numberFormatOptions: {separator: "."}
errorMessage: "Failed to get CSRF token 500"
__proto__: ErrorState
__proto__: CoreBase
__proto__: CoreBase


Do you know how to bypass this error?
Env : CE multitenant
Odin : 2.2.1
Service call : 
  this.userService.getUserContext().subscribe((userContext: IUserContext) => {
         this.userContext = userContext;
      }

thanks.
