### ISSUE TITLE
Is that possible to launch a program with parameters?

### ISSUE THREAD

**Issue by Xiang-Ji615** [infor-cloud/m3-h5-sdk#29]
Hi,

Can I pls ask if that's possible to launch MI program with parameters?
Eg, open MMS001B with prefilled ITNO and then filter the data
Thx.

**Comment by karinpb** [comment]
Hi,
No there is no support for that in M3. There is however something called passing an Automation XML and if you build H5 Scripts there is a Util MFormsAutomation that you can use and build a step by step instruction in XML that would mimic and replay user actions on a the H5 server before the panel is returned so it's possible to do that, but you need to know the fields and basically it's not what we would recommend. We would recommend using a bookmark going to some detail. I don't think they have positioning support for bookmarks, but that could be something to consider as an M3 requirement.

I'll check with the M3 team, perhaps there is a functional search query that can be used.

There are some questions on Automation here (if you search on the page), but note that it is for H5 Scripting. https://smartofficeblog.com/h5-scripting/ 

The enhancement here would be if we should support Automation Xml or not in the SDK and since we want bookmarks to be used I don't think we'll be adding that support, but we can discuss it in the team,

**Comment by karinpb** [comment]
I checked with M3 and you can do a search type of bookmark if that table is enabled for search. This might be helpful: https://www.inforxtreme.com/espublic/EN/AnswerLinkDotNet/SoHo/Solutions/SoHoViewSolution.aspx?SolutionID=1687355&kb_accessed_from=KBViews

**Comment by Xiang-Ji615** [comment]
Thx, I gave a try with automation and that works well.
