### ISSUE TITLE
How to override program close button event using SDK?

### ISSUE THREAD

**Issue by ErrorCode101** [infor-cloud/m3-h5-sdk#32]
Hi,

We are using m3-odin 2.1.2 with angular 7 to build an infor M3 application.

We have a requirement to show a confirmation message to user whether to close the application or not depending on the certain details entered in the program. Is there anyway to achieve this?

**Comment by karinpb** [comment]
Currently no. This would require a change in the H5 client. As such the way would be to create an Xtreme support ticket requesting this functionality in H5 MUA. An enhancement like this would only be done for cloud. 

Since H5 owns the tab they would have to implement some kind of post-message API to ask the application if it is OK to close it and then wait x seconds for an reply before closing it. Since there is no manifest that can describe the intentions of an application this would affect all applications unless an manifest was added.

It seems like a small request, but this is actually a lot of work. Since it needs to be done in H5 before we can implement it in the H5 SDK I kindly ask you to create an enhancement request for it.

Are there more developers interested in this? Let us know.
