### ISSUE TITLE
m3-h5-sdk upgrade for an existing project 

### ISSUE THREAD

**Issue by aleste37** [infor-cloud/m3-h5-sdk#37]
## Description
https://github.com/infor-cloud/m3-h5-sdk/issues/27 describes an issue in @infor-up/m3-odin-angular  2.2.0  that has been fixed in version 2.2.1.   Is there a recommended set of steps to upgrade an existing project?

**Comment by anhallbe** [comment]
Upgrading minor/patch can usually be done with `npm install package@version` or `ng update package@versionOrTag`, since they should not have breaking changes in the API.

Some examples:

```
npm i @infor-up/m3-odin@2.2.1
npm i @infor-up/m3-odin@latest
ng update @infor-up/m3-odin @infor-up/m3-odin-angular
npm i @infor-up/m3-odin-angular@2.2.1
npm i -g @infor-up/m3-odin-cli@2.2.1
```

You could also run `npm outdated` and `npm update` to update your dependencies, depending on what you have specified in package.json.

**Comment by alliancehaydenm** [comment]
Hi team, thanks for the help. I seem to be getting a HTTP 404 error during the install command - see attached. My proxy settings are auto-detect in windows; and all other internet functions are working as normal. Any ideas/config settings I need here?

![image](https://user-images.githubusercontent.com/62520530/79401507-6491d400-7fdd-11ea-839f-472d3183fff2.png)

**Comment by anhallbe** [comment]
@alliancehaydenm that issue is probably caused by an incompatible node.js version. Projects created with the Odin CLI is currently using an older version of Angular CLI (will be upgraded ASAP), which depends on an older version of node-sass, which depend on an older version of node.js.

See here for compatible node.js runtimes: https://github.com/sass/node-sass/releases/tag/v4.10.0

**Comment by anhallbe** [comment]
The `next` version 3.0.0 (see https://github.com/infor-cloud/m3-h5-sdk/releases ) with updated dependencies no longer uses node-sass, which was causing the install issue
