### ISSUE TITLE
SDK security by IFS roles

### ISSUE THREAD

**Issue by Ouse** [infor-cloud/m3-h5-sdk#38]
## Description
Hi I would like to set the security for a m3 sdk allowing different functionality depending if the user belongs to specific IFS Roles, so for example we have Admin user that can delete/create records and Viewers users that just can see the information. The first thing will be retrieve the IFS roles of the user that is executing the SDK, is there an API for that?

## Versions
I want to use this in MT-Cloud and also in M3 13.4/InforOS 12.0.37

**Comment by karinpb** [comment]
There is no API for that and I'm not sure if we should add one. What backend are you calling? The roles has to be evaluated there. Adding security checks in the client is just usability, it's not security. If you have the backend then you should ask it for user permissions instead of coding for specific roles, since you still need to add code to the backend to handle the roles. I'm skeptical to adding functionality for this by allowing roles to be returned directly to the client.

This gives a false sense of security because the UI for delete/create is not there, but unless the server actually enforce that, there is no security in place. If the server can enforce it then the server should be able to return permissions.

I would suggest checking the M3 roles to see if there is an API for that so that you can also configure security for the APIs that you are planning to use.

We might consider requesting the IFS team to add an API where you can check against a list of roles that you pass in, but that would only be for usability. Today there is no such API, so there is no API that you can use for IFS roles, but you still need to consider if it is security that you are after and not usability.

To ask Infor to add an API for this try an enhancement request or contact support. It has to be added in IFS before this SDK can add an API for accessing it. These apps are independent so we might not add a caching API at all for it, you are free to call any API that exists in the ION API Gateway.
