### ISSUE TITLE
Unable to launch Ion IMS Ion API

### ISSUE THREAD

**Issue by thememphis** [infor-cloud/m3-h5-sdk#40]
Hi all,
I'm trying to run acceptedDocuments API from IONSERVICES/api/ion/messaging/service/v3
This API requires ClientID (also in ION API Documentation).
I've added X-ClientID to headers before I launch that, but everytime the API returns me a "fail" error that states:

status: "FAIL"
code: 471
errors: "Invalid client id provided"

With postman it all works correctly.
The clientID it's the same I have in my ION Desk IMS Connection point.
I really don't understand how I can launch that API.
It seems that the API call can't be done correctly.
All others (IDM, Ming.le, etc from samples) works just fine.

I'm in multi-tenant environment.

Thanks a lot for your answers and help.
Davide

**Comment by anhallbe** [comment]
This seems like an application-specific issue with no strong relevance to the H5 SDK, since other ION API endpoints work as expected. I'm not familiar with the API, and nobody here seems to have an idea on how to solve it.

If you still think this is an issue with the SDK, please file a bug report with repro code and instructions. Thanks
