### ISSUE TITLE
Error while running ION API request from H5 SDK 

### ISSUE THREAD

**Issue by melghobashi** [infor-cloud/m3-h5-sdk#50]
I deployed the sample on H5 and while running the ION request I faced the following issue 
GET https://{server}/grid/rest/security/sessions/oauth?rid=WT6IH0WQSDELNQVR 404 (Not Found)
![image](https://user-images.githubusercontent.com/66242051/83385111-ea7ca980-a3e8-11ea-9a2b-1a8509c162c9.png)

that causes to not authenticating with the ION API.
Can you advice what may be the issue ?

**Comment by karinpb** [comment]
Hi,
Is that resolved to the H5 server? I guess it has to, because I did a search for /grid/rest/security in this project, I mean all the code is here, and it's a relative path. So either the grid has moved the API endpoint to get a token without telling us, OR you are not running the H5 SDK in a cloud version of M3. 

ION API calls ONLY works on cloud because there is no way for us to get the token required on a 1.13 grid, which would be the grid that you have in an older M3.

So sorry you can't run the social sample on an on-prem M3.
