### ISSUE TITLE
[experimental-login] MIService in local development environment

### ISSUE THREAD

**Issue by hldarshana** [infor-cloud/m3-h5-sdk#55]
Hi,

Can we use new experimental-login feature to test MIService in local development environment? If so, is there any example (including how to set ionApiConfig and it's path) to refer?

Thank You

**Comment by anhallbe** [comment]
Yes! You can use the experimental-login command since version 3. More detailed docs are on their way.

This is a new (experimental) feature. So please try it out, and all feedback/issue reports are appreciated.

In short, the steps are:
1. Configure and download an .ionapi file (see below)
2. Run `odin experimental-login ./path/to/downloaded-file.ionapi`
  2.1 Add the `--update-config` or `-c` flag to the above command to automatically update `odin.json`. So `odin experimental-login -c .....`
3. Run `odin serve --multi-tenant --ion-api`

Now, requests to e.g `/m3api-rest` will be redirected to the configured ION API endpoint in the development proxy.

You can also configure it so that requests will be proxied directly to M3, without the ION API in between. This may be necessary if for instance the M3 API you are using is accessible through ION API:
1. See step 1 above. The ION API config is still needed for login.
2. Run `odin experimental-login --update-config --m3 https://url.to.m3 ./path/to/downloaded-file.ionapi`
3. Run `odin serve --multi-tenant`

## Configuring ION API
You should look into the ION API documentation for more detailed instructions on what to do (**and what NOT to do**). Make sure you are aware of the security implications of authorizing apps like this. But the following is one way to do it:
1. Go to the InforOS portal, and open the ION API application:
![1-open-ionapi](https://user-images.githubusercontent.com/4991954/86115893-d94cb880-bacc-11ea-9aaf-d00da7e994e6.png)
2. Go to the "Authorized Apps" section and "Add new app":
![2-authorized-apps](https://user-images.githubusercontent.com/4991954/86115952-f1bcd300-bacc-11ea-9311-c16a72f93b3b.png)
3. Configure it something like this, and "Save" it:
![3-config](https://user-images.githubusercontent.com/4991954/86116097-29c41600-bacd-11ea-9e21-aff4bef4217b.png)
4. Download the .ionapi file:
![4-download-credentials](https://user-images.githubusercontent.com/4991954/86116249-6728a380-bacd-11ea-8c19-e26a145e1826.png)

**Comment by bjohog** [comment]
Have tested this but encountered below error:

![image](https://user-images.githubusercontent.com/39406230/86125605-3c464b80-badd-11ea-9a45-d138159dce92.png)

![image](https://user-images.githubusercontent.com/39406230/86125632-48caa400-badd-11ea-9e5a-2966779a5bae.png)

![image](https://user-images.githubusercontent.com/39406230/86125643-4d8f5800-badd-11ea-9792-7a83a55a2786.png)

**Comment by swuendri** [comment]
Are there any open points @hldarshana here? If not close the issue please.
