### ISSUE TITLE
Datagrid Initial Paging information not displayed.

### ISSUE THREAD

**Issue by LucasLund** [infor-cloud/m3-h5-sdk#57]
## Description
*Please describe your problem in detail. Including code snippets, logs and screenshots is encouraged. Just make sure you do not provide any sensitive information like user details, login credentials, authentication tokens etc.*
I've created a DataGrid with Paging using a Service following the examples in the enterprise-ng repository.
But on initial load of the DataGrid, the pager at the bottom displays [PageOf] and [RecordsPerPage] until I switch to a different page, where it will then display the correct "Page 2 of X" and "10 Records per Page".

I asked over at the enterprise-ng repository as well and they told me it might have a relation to the Locale that's used, but referenced me over here since they don't have much knowledge on the M3-H5-SDK.
I haven't changed any of the default setup that's made when creating the application via Odin.

## Versions
*Please include the version numbers of the software related to the question, if applicable.*
Odin Version 3.0.1
ids-enterprise-ng 7.2.0
infor-up/m3-odin 3.0.1
infor-up/m3-odin-angular 3.0.1

**Comment by LucasLund** [comment]
The post on their repository is the following:
https://github.com/infor-design/enterprise-ng/issues/861

**Comment by anhallbe** [comment]
Yep, definitely an issue with locale. I see there may be a mistake in the sample project. The problem is that the locale initializer returns a promise, but the app does not wait for the promise to resolve before continuing initialization. So translations are not applied directly (if the timing is right). Could you try changing the following, and see if the issue is still there?

src/app/app.module.ts
```typescript
         useFactory: (locale: string) => () => {
            Soho.Locale.culturesPath = 'assets/ids-enterprise/js/cultures/';
            Soho.Locale.set(locale); // change this
            return Soho.Locale.set(locale); // ...into this
         },
```

**Comment by LucasLund** [comment]
Yes! That fixes the issue, thanks a lot :)

**Comment by tmcconechy** [comment]
@anhallbe is anything special the API needed to use this approach. This seems a little simpler than what we are doing with the SohoLocaleInitializer...

**Comment by anhallbe** [comment]
@tmcconechy nope, it should work quite well for any new Angular project with `ids-enterprise-ng`.

However, the `SohoLocaleInitializer` is a bit more sophisticated in that it works if the app is deployed with another `baseHref` or `deployUrl`. It also looks like it has some things for extending the translations, which is nice. But just returning the Promise from `Soho.Locale.set` works fine otherwise. Though it might be a good idea to catch any errors as to not prevent the rest of the app from loading:
```typescript
  return Soho.Locale.set(locale).catch(err => log("Error when setting locale. Some translated strings might look off"));
```
