### ISSUE TITLE
Upgrade dependencies to use ids-enterprise-ng 6.0.0 and Angular 8

### ISSUE THREAD

**Issue by hernebrink** [infor-cloud/m3-h5-sdk#6]
Feature request: Update dependencies to use ids-enterprise-ng 6.0.0

When creating a new application with the Odin Cli you will get ids-enterprise-ng  version 5.0.0 and angular 7.1. It would be nice if this can be bumped to use Angular 8.x.x and ids-enterprise-ng 6.0.0.

**Comment by anhallbe** [comment]
Agreed!
This has been kind of put on hold since the upgrade process is still a mess. I.e upgrading a project from Odin vX to vY. But it's definitely something that should be fixed ASAP.

There are also a number of dependencies that need security updates..

**Comment by anhallbe** [comment]
This will probably be implemented once Angular 9 and a compatible version of ids-enterprise-ng lands.

**Comment by cerjoh** [comment]
Are there any workarounds to get an up-to-date version of ids-enterprise-ng to work with the Odin framework? I tried upgrading within project, but it seems Odin cannot handle Angular 8. 

ids-enterprise-ng@5.0.0 is soon a year old and a lot has happened in terms of features and removed bugs.

**Comment by cerjoh** [comment]
> This will probably be implemented once Angular 9 and a compatible version of ids-enterprise-ng lands.

Angular 9 is here and ids-enterprise-ng is up to speed. This repo is lacking when it comes to features and, most importantly, security. Can we get an update on when we can expect a new release?

**Comment by cerjoh** [comment]
Hi! Any update on this? Customers are using this now and we need this framework up to date. Can we contribute in any way?

**Comment by anhallbe** [comment]
Hi @cerjoh! Sorry for the delayed response.

There is a pre-release version available for the CLI and packages (will eventually be 3.0). It mostly includes changes to dependencies, so it should be quite stable. Although it has not yet been properly tested or documented, and the upgrade process for existing projects can be a bit tricky. They're published under the `@next` tag, so if you want to try it out (and contribute through testing) you can:

1. Install the CLI: `npm i -g @infor-up/m3-odin-cli@next`
2. Upgrade dependencies to existing projects:
   - `ng update @infor-up/m3-odin@next @infor-up/m3-odin-angular@next @angular/core @angular/cli ids-enterprise-ng codelyzer typescript@3.8` see https://update.angular.io/ for further instructions.

The (known) breaking changes included so far are:
- Requires NodeJS version >=12.16.3 (current LTS)
- Requires Angular 9, which has some breaking changes since 7.0.
- `ids-enterprise-ng@7` requires slightly different configuration. There's currently no way to automatically reconfigure while upgrading, so you'd have to check https://github.com/infor-design/enterprise-ng/blob/master/docs/QUICKSTART.md and do it manually. New projects will be configured correctly, though.

**Comment by anhallbe** [comment]
Version 3 is now available with IDS 7.x and Angular 9.x
