### ISSUE TITLE
Chartstack application not working as in-context app - in Cloud MT

### ISSUE THREAD

**Issue by Magalie-aut** [infor-cloud/m3-h5-sdk#61]
We have an issue with ChartStack 2 Application - it used to work fine until suddenly we have lost all the graphs created as in-context and can not recreated them. ChartStack still works when not in-context.
We have reported this issue to Infor Support (case 14608568) and the conclusion is that it now requires the applications to be changed - but noone can look into it for now. However, as it is open source so the project can be changed and a MR can be submitted - and Infor Support suggested we report this here .. 

To Reproduce: 
In MT Cloud environment - we have a CloudSuite Distribution Entreprise - Set-up ChartStack as in-context app. No chart can be created - options to create are not  there

In our on-prem environment it works fine. 
[chartstack2_1.zip](https://github.com/infor-cloud/m3-h5-sdk/files/4986557/chartstack2_1.zip)

**Comment by drirem0** [comment]
Hi Megalie., I think this has to do that infor.companyon doesn't seem to work on multi tenant. I experienced the same thing.., I was successfully using sendmessage inforbusinesscontext from on prem  , but it complains under multi tenant

**Comment by karinpb** [comment]
Hi, Chartstack 2 uses the H5 SDK 1.0 which is this SDK but it’s not in this repro as it is version 1.0. I think the assumption was that the chartstack used the 2.0 version. The issue here is caused by an endpoint that the SDK uses in the grid. We thought it was a public API to get user information from the grid, but it wasn’t since it wasn’t documented as an API in their documentation. The endpoint is only called when running the application as a context application.

On prem and MT of M3 uses two different versions of the grid. The API changed sligtly so Odin 1.0 has been updated with a fix to parse the user information. The errorhandling in the application is not that good so when the user can't be determined it's just blank,

What you need to do is to update the Odin part of the application with the Odin v1 that you got from support, that has the fix for this issue, and then create a runtime build of the application. What you attached is the source and it should not be what you are uploading and deploying as an application in H5. 

They will probably add more validation when this is more used and then it would reject any .ts files as those are source files. 

I'll see if we can help you out with updating the application, just this one time. It's important to be able to apply updates regulary if required to an application and I can't guarantee that I'll be able to find someone that can update the application nor that it it's possible as the zip might not contain all the information needed.

**Comment by karinpb** [comment]
@drirem0
infor.companyon works on both MT and on-prem. 

It's what all Infor products are using. So there is something else going on. Security is more tight in on-prem for example. The companyon client only works in one level of IFrames unless you use a new type of proxy message that was added to support a new scenario for Ming.le Homepages. Depending on the scenario my assumption is that you are using the companyon client in a way that is not supported but there is a difference in the environments that you are testing it is. When you say that "it compains under multi tenant" it indicates that there is an error message. You should try and ask your question in the Infor Community forum, https://community.infor.com/infor-ming-le/ or contact support, although developer related queries are not supported so in that case a developer need to push it as a bug and then you need to have a developer working on the issue with a lot of web development experience. I try to answer stuff in the community as well, if I have time.

**Comment by Magalie-aut** [comment]
Hello, thanks for your comments - we indeed had to have a new version of the application, and the problem is solved now!

**Comment by karinpb** [comment]
Ok, so the issue is solved and you don't need any more assistance? I'm glad that it worked out.
