### ISSUE TITLE
Send Process.Workflow

### ISSUE THREAD

**Issue by Ouse** [infor-cloud/m3-h5-sdk#64]
## Description
I would like to create a button on a M3 panel to triger a ION Workflow.
Is it possble to send a Process.Workflow from a H5 Script?

## Versions
M3 16 MT.

**Comment by karinpb** [comment]
Yes, as long as they have an API for that exposed in ION API AND you are on M3 CE. Only M3 CE supports getting the token that you need to authenticate since it runs on Grid 2.0.

But what to call etc you need to check the documentation for ION Process. I would start by checking the APIs available in ION API.
