### ISSUE TITLE
What is purpose of classes Panel, FormControl, FormService and its interfaces?

### ISSUE THREAD

**Issue by adityabhatkhande-avaap** [infor-cloud/m3-h5-sdk#66]
I went through the API documentation where I saw some classes including Panel, FormControl and FormService along with their interfaces. 
Are these classes used to interact with M3 screens? I could not find any more information on the same. Can somebody please tell how to use these classes?

**Comment by anhallbe** [comment]
Yes, these classes are for interacting with M3 screens. However, the documentation for these are intentionally left out since interactive programs are too complex for most developers and should only ever be used for edge cases. It can be used for custom rendering of stateless detail panels started using a bookmark.

There is a basic example of using the FormService in the "bookmark" sample.

**Comment by Ouse** [comment]
Hi,

I checked that sample Bookmarks, and as you mention it is read-only.

So the 'best' way to approach requirements where a panel in M3 needs to added to a sdk, like we composed screens with the old Smart Office Mashups Designer will be to avoid it and try to list M3 APIs?, even if we lose the M3 functionality to it?.

Tack!.

**Comment by anhallbe** [comment]
Yes, the recommended approach is to use the M3 API:s. If the API is lacking functionality, then please contact M3 support for any enhancement requests.
