### ISSUE TITLE
Calling M3 MI Transactions through IONAPI in future ?

### ISSUE THREAD

**Issue by drirem0** [infor-cloud/m3-h5-sdk#79]
Hello, 

We have lined up quite a few H5SDK development work. We're able to call M3 API's through MIService, like the native M3 way, and from odin version 3.0.2., now IONAPI also works well. 

Going forward., would you advise that within H5SDK we should configure/develop M3 API's through IONAPI from now on as you might disallow us to use the authentic MIService M3 API's in future ?   or are there no plans as such and MIService will be kept open for future aswell within H5SDK development ?

Thanks
Remco

 const request: IMIRequest = {
            program: 'CMS100MI',
            transaction: 'LstM631S01',
            record: input,
            outputFields: ['MBWHLO', 'MBITNO', 'MMITDS', 'MMITGR', 'MMITCL', 'MMITTY', 'MMSTAT', 'MMRESP', 'MMQACD', 'MMFUDS', 'MMSPUN', 'MMUNMS', 'MMSACD', 'MBWHSL'],
            maxReturnedRecords: this.maxRecords
         };
         this.miService.execute(request).subscribe((response: IMIResponse) => {

**Comment by karinpb** [comment]
Hi, There are no plans to move to ION API. BUT you should have a dataservice that make all the calls. Becuase you never know when there is a requirement to add a specific header or whatever. So make sure to have calls to MI in a service so that you have it all in one place to make the changes easy to apply. For example have only ONE method to call this.miService.execute(request).subscribe((response: IMIResponse), because it make it's easier to switch and add stuff.  Like the miService has an execute method, your dataservice should only have one execute service. It makes maintaining easier. 

I think the IDM service example demponstrate just that. How to build a service that can both call ION API and another endpoint.
