### ISSUE TITLE
Failed to get CSRF token - Unable to get userContext

### ISSUE THREAD

**Issue by MoAShark** [infor-cloud/m3-h5-sdk#95]
I am having the below error when trying to run (on multi tenant) the new  sample project which is created by the (odin) new command. I am using the login utility OdinSDKMTLoginUtility for authentication. I also can run this sample (infor-m3-odin-sample-soho-4.0.0) without issues on multi-tenant.
![image](https://user-images.githubusercontent.com/83918202/117585504-0ae1d780-b113-11eb-9a71-5246872a9e44.png)

**Comment by anhallbe** [comment]
Hi!
These issues are usually pretty hard to diagnose since it is related to either configuration (`odin.json`) or backend service auth/connection.

Make sure that `odin.json` looks correct, specifically the target for `/m3api-rest`. Also make sure you add the `--multi-tenant`, and `--ion-api` (if applicable) flags to `odin serve`, depending on how you want to set things up:

![login flowchart](https://user-images.githubusercontent.com/4991954/110319955-dfa61380-800f-11eb-8068-4a974fb286a8.png)

You could also try using the `odin login` command instead of the MTLoginUtility.
The process is described here: https://github.com/infor-cloud/m3-h5-sdk/issues/55#issuecomment-651713612
